### PR TITLE
Added Range Get Test for Multiple Clients

### PR DESCRIPTION
**Pull request by windkit**
1.aws-sdk-java
2.aws-sdk-php
3.aws-sdk-duby
4.boto (Python)
5.erlcloud (Erlang) * Patch v.0.8.0

Updated README for instructions

### CODE REVIEW

**Comment by windkit** [comment]
Updates to test Range Get for Large Files (Multipart/Single Put)

**Comment by yosukehara** [comment]
I've merged your request with [support-range-object](https://github.com/leo-project/leofs_client_tests/commits/support-range-object).

**Comment by yosukehara** [comment]
@windkit I've briefly check your request. I cannot finish the test correctly. It seems range-object test  have failed. Can you check them?

### For Java client
* Error:
```
run:
    [javac] /Users/yosuke.hara/dev/leo-project/test/leofs_client_tests/aws-sdk-java/build.xml:12: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
     [java] Bucket Creation Test [Start]Jun 16, 2015 2:04:42 PM com.amazonaws.http.AmazonHttpClient createHttpClient
     [java]
     [java] INFO: Configuring Proxy. Proxy Host: localhost Proxy Port: 8080
     [java] Bucket Created Successfully
      .
      .
      .
     [java] GET non-existing Object Test [Start]
     [java] The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: test/testFile.noexist)
     [java] 404
     [java] GET non-existing Object Test [End]
      .
      .
      .
     [java] Range Get Object Test [Start]
     [java] Range Get in Small Object
     [java]
     [java] Exception in thread "main" java.io.IOException: Range Get Result does NOT match
     [java] 	at LeoFSSample.main(Unknown Source)
     [java] Java Result: 1
```
OR
```
run:
    [javac] /Users/yosuke.hara/dev/leo-project/test/leofs_client_tests/aws-sdk-java/build.xml:12: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
     [java] Jun 16, 2015 2:05:53 PM com.amazonaws.http.AmazonHttpClient createHttpClient
     [java] INFO: Configuring Proxy. Proxy Host: localhost Proxy Port: 8080
     [java] Bucket Creation Test [Start]
     [java] Bucket Created Successfully
      .
      .
      .
     [java] GET non-existing Object Test [Start]
     [java] Exception in thread "main" java.io.IOException: Range Get Result does NOT matchThe specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: test/testFile.noexist)
     [java]
     [java] 404
     [java] GET non-existing Object Test [End]
     [java]
     [java] 	at LeoFSSample.main(Unknown Source)
     [java] Range Get Object Test [Start]
     [java] Range Get in Small Object
     [java]
     [java] Java Result: 1

**Comment by yosukehara** [comment]
In addition, I've checked latest LeoFS (brach of every leo's lib is develop) as below. There is no issues.

```bash
$ s3cmd put VirtualBox-4.3.28-100309-OSX.dmg s3://test/
VirtualBox-4.3.28-100309-OSX.dmg -> s3://test/VirtualBox-4.3.28-100309-OSX.dmg  [1 of 1]
 114102333 of 114102333   100% in    1s    69.80 MB/s  done
 
$ leofs-adm whereis test/VirtualBox-4.3.28-100309-OSX.dmg
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
 del?  |           node           |             ring address             |    size    |   checksum   |  # of chunks   |     clock      |             when
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
       | storage_0@127.0.0.1      | 9b0ea7bb197bc8bbc296698bb070fc4c     |    111428K |   5bd31266c4 |             22 | 5189c31299bfa  | 2015-06-16 14:53:22 +0900

$ curl --range 1048576-10485760 http://localhost:8080/test/VirtualBox-4.3.28-100309-OSX.dmg   -o test_0.dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9216k  100 9216k    0     0   168M      0 --:--:-- --:--:-- --:--:--  169M

$ curl --range 0-0 http://localhost:8080/test/VirtualBox-4.3.28-100309-OSX.dmg   -o test_1.dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     1  100     1    0     0     99      0 --:--:-- --:--:-- --:--:--   111
```

**Comment by windkit** [comment]
As it is supposed to print out the line read from the Range Response at 
https://github.com/leo-project/leofs_client_tests/blob/9885b2bf7a411faddb5a8346c975b8dc4893b710/aws-sdk-java/LeoFSSample.java#L221
The error seems suggesting it failed to get a valid reply from `leo_gateway`

Unfortunately, I still cannot reproduce the error after I checked out the develop branch
- Clean Clone of leo-project/leofs, modify rebar.config for
  - `leo_manager` : {branch, "develop"}
  - `leo_storage` : {branch, "develop"}
  - `leo_gateway` : {branch, "develop"}

I confirm the range get (1048576-10485760) issue is fixed with develop branch of `leo_storage` and `leo_object_storage`

**Comment by yosukehara** [comment]
@windkit  I've checked our environment then Java and Ruby clients work fine.
Thank you for your contribution.

**Pull request merged**
